### PR TITLE
Enable Windows builds

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Just checking how difficult it is to support Windows...

**Comment by dhirschfeld** [comment]
There's an odd error after the build finishes (apparently) successfully:
```
    Finished release [optimized] target(s) in 2m 25s
💼 Using the existing cbindgen.toml configuration. 
💼 Enforcing the following settings: 
   - language = "C" 
   - no_includes = true 
   - no include_guard 	 (directives are not yet supported) 
   - no defines       	 (directives are not yet supported)
📦 Built wheel to C:\Users\VSSADM~1\AppData\Local\Temp\build-via-sdist-26p5nv8v\arrow_odbc-1.3.2\target\wheels\arrow_odbc-1.3.2-py3-none-win_amd64.whl
C:\Users\VSSADM~1\AppData\Local\Temp\build-via-sdist-26p5nv8v\arrow_odbc-1.3.2\target\wheels\arrow_odbc-1.3.2-py3-none-win_amd64.whl
Successfully built arrow_odbc-1.3.2.tar.gz and arrow_odbc-1.3.2-py3-none-win_amd64.whl
WARNING: Requirement 'dist/*.whl' looks like a filename, but the file does not exist
ERROR: *.whl is not a valid wheel filename.
```

...after which no files are found in the package:
```
2023-11-10T13:18:34.7910735Z Packaging arrow_odbc
2023-11-10T13:18:34.8258759Z Packaging arrow_odbc-1.3.2-py310h87d50f1_1
2023-11-10T13:18:34.9181083Z WARNING: No files or script found for output arrow_odbc
```

...which then results in an import error in the test:
```
import: 'arrow_odbc'
Traceback (most recent call last):
  File "D:\bld\arrow_odbc_1699621536412\test_tmp\run_test.py", line 2, in <module>
    import arrow_odbc
ModuleNotFoundError: No module named 'arrow_odbc'
```

**Comment by dhirschfeld** [comment]
So, it seems to not be liking this line:
https://github.com/conda-forge/arrow_odbc-feedstock/blob/804f2885ba1e12255417dc83253f5ff7addbcaa7/recipe/meta.yaml#L19

For comparison, the successful linux build has the below output:
```
2023-11-10T13:08:08.0965528Z 📦 Built wheel to /tmp/build-via-sdist-9fe6e1xo/arrow_odbc-1.3.2/target/wheels/arrow_odbc-1.3.2-py3-none-linux_x86_64.whl
2023-11-10T13:08:08.0988127Z /tmp/build-via-sdist-9fe6e1xo/arrow_odbc-1.3.2/target/wheels/arrow_odbc-1.3.2-py3-none-linux_x86_64.whl
2023-11-10T13:08:08.1769828Z Successfully built arrow_odbc-1.3.2.tar.gz and arrow_odbc-1.3.2-py3-none-linux_x86_64.whl
2023-11-10T13:08:08.8616087Z Processing ./dist/arrow_odbc-1.3.2-py3-none-linux_x86_64.whl
2023-11-10T13:08:08.8706663Z Installing collected packages: arrow-odbc
2023-11-10T13:08:08.9191167Z Successfully installed arrow-odbc-1.3.2
```

**Comment by dhirschfeld** [comment]
If we go back a bit in the logs, for linux we can see:
```
📦 Built source distribution to /home/conda/feedstock_root/build_artifacts/arrow_odbc_1699621348356/work/dist/arrow_odbc-1.3.2.tar.gz
```

And for Windows:
```
📦 Built source distribution to D:\bld\arrow_odbc_1699621536412\work\dist\arrow_odbc-1.3.2.tar.gz
```

**Review by jonashaag — APPROVED** [review]

**Pull request merged**
